# Configuration file for the Sphinx documentation builder.
#
# Narrative documentation is written in MyST Markdown and rendered by Sphinx
# with the Furo theme. The C/C++ API reference is generated by Doxygen (XML)
# and embedded via the Breathe extension. docs/build.py runs Doxygen first,
# then this Sphinx build.

import os

# -- Project information -----------------------------------------------------
project = 'pals-cpp'
copyright = '2026, pals-cpp Contributors'
author = 'pals-cpp Contributors'

# -- General configuration ---------------------------------------------------
extensions = [
    'myst_parser',              # MyST Markdown
    'breathe',                  # Doxygen XML -> Sphinx
    'sphinx.ext.githubpages',   # emit .nojekyll for GitHub Pages
    'sphinx.ext.mathjax',
]

numfig = True

# -- Breathe (Doxygen bridge) ------------------------------------------------
# Doxygen writes its XML to docs/doxygen/xml (see docs/Doxyfile and build.py).
# The path is relative to this conf.py, which lives in docs/src.
breathe_projects = {'pals-cpp': '../doxygen/xml'}
breathe_default_project = 'pals-cpp'
breathe_domain_by_extension = {'h': 'cpp', 'hpp': 'cpp'}
breathe_show_include = False

# -- MyST configuration ------------------------------------------------------
myst_enable_extensions = [
    'dollarmath',
    'amsmath',
    'deflist',
    'colon_fence',
    'linkify',
]
myst_heading_anchors = 3

# -- HTML output (Furo) ------------------------------------------------------
html_theme = 'furo'
html_theme_options = {
    'source_repository': 'https://github.com/pals-project/pals-cpp',
    'source_branch': 'main',
    'source_directory': 'docs/src/',
    'navigation_with_keys': True,
    'sidebar_hide_name': False,
}
html_title = 'pals-cpp'
